### PR TITLE
Added WCS to SimpleSimulator

### PR DESCRIPTION
**Pull request by jfcrenshaw**
I added a WCS to `SimpleSimulator`. This is accomplished on instantiation by shooting 25 photons on a grid across the focal plane and fitting using [`galsim.FittedSIPWCS`](https://galsim-developers.github.io/GalSim/_build/html/wcs.html#galsim.FittedSIPWCS).

I save the WCS under `simulator.wcs`, which allows you to do any of the WCS things you would like to do.

I also added a method `get_bounds` which will return the bounds on the field angles that hit the simulated sensor. You can change the unit of these angles, but the default is radians, as `add_star` expects field angles in radians.

### CODE REVIEW

**Comment by jfcrenshaw** [comment]
Oh sorry, there are lots of changes just from the fact that my editor automatically runs the `black` formatter on the code. I can roll back those changes if you want.

**Comment by jfcrenshaw** [comment]
I also fixed an error where the `R40` and `R04` wavefront sensors had the wrong orientations.

**Comment by jmeyers314** [comment]
Code looks good to me (aside from the blackening). 

The notebook is great, though for me it looks like the FFT algorithm failed for some reason?  I wonder if it always fails or if we got an unlucky set of donuts.  Maybe try some different parameters?

Also, I generally save notebooks without the images rendered.  Since git stores the complete history, rerunning and then recommitting notebooks with images can quickly increase the size of the repo.  (Exceptions do occur when I expect the notebook to not get updated, but I think `cwfs-simulation` may continue to evolve.)

> Oh sorry, there are lots of changes just from the fact that my editor automatically runs the black formatter on the code. I can roll back those changes if you want.

Yeah, sorry.  I'm not a fan of `black` in general.  Please do the roll back.

I think we'll also need to rethink some of this when simulating with the rotator engaged since then the thx, thy bounds will be more diagonal.  But we can save that for a future PR.

**Comment by jfcrenshaw** [comment]
Oh that is smart about the notebooks - I haven't thought of that before! I will remove the outputs from the history.

I will also roll back the `black` formatting.

re: the FFT failing, I was investigating that myself and made [this gist](https://gist.github.com/jfcrenshaw/1c04d8fb0b4e66ef1bc87115ee44cbcc) to replicate the problem. It looks like it fails whenever `thx != thy`, which seems strange. I don't know if this is a bug or user error on my part. (note the gist also contains one other problem I want to bring up in the AOS meeting)

**Comment by jfcrenshaw** [comment]
I cleared notebook outputs and rolled back the changes that black made.

I will merge this now.

**Pull request merged**
